Eigenvalues and Eigenvectors

In [52]:
import numpy as np
from numpy.linalg import svd

In [49]:
A = np.array([[6, 2], 
      [3, 5]])
A

array([[6, 2],
       [3, 5]])

In [50]:
eig_value, eig_vector = np.linalg.eig(A)

In [51]:
print('The Eigenvalues are: ',eig_value)
print('The Eigenvectors are: ',eig_vector)

The Eigenvalues are:  [8. 3.]
The Eigenvectors are:  [[ 0.70710678 -0.5547002 ]
 [ 0.70710678  0.83205029]]


Singular Value Decomposition

In [53]:
A

array([[6, 2],
       [3, 5]])

In [54]:
Left, Mid, Right = svd(A)

print('Left SV:',Left)
print('SV:',Mid)
print('Right SV:',Right)

Left SV: [[-0.7438189  -0.66838121]
 [-0.66838121  0.7438189 ]]
SV: [8.07219027 2.97317075]
Right SV: [[-0.80127658 -0.5982941 ]
 [-0.5982941   0.80127658]]


Determinant

In [55]:
A

array([[6, 2],
       [3, 5]])

In [56]:
np.linalg.det(A)

23.999999999999993